theme: jekyll-theme-minimal
title: Kit McDonnell
description: Kit McDonnell's website is currently under construction as 
she revisits her freshman-year coding days. To keep up with her latest 
antics, please visit her impavid Instagram (http://www.instagram.com/kitmcdonnell).
